/*
 * Copyright 2011, The gwtquery team.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.gwt.query.client.css;

import com.google.gwt.dom.client.Style;

/**
 * This property specifies the content height of boxes generated by block-level,
 * inline-block and replaced elements.
 *
 * This property does not apply to non-replaced inline-level elements. See the
 * section on computing heights and margins for non-replaced inline elements for
 * the rules used instead.
 */
public class Height implements TakesLength, TakesPercentage {

  public Height() {
  }

  public static void init() {
    CSS.HEIGHT = new Height();
  }

  public void set(Style s, Length value) {
    s.setProperty("height", value.value());
  }

  public String get(Style s) {
    return s.getProperty("height");
  }

  public void setLength(Style s, Length p) {
    s.setProperty("height", p.value());
  }

  public void setPercentage(Style s, Percentage p) {
    s.setProperty("height", p.value());
  }
}
