/*
 * Copyright 2011, The gwtquery team.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.gwt.query.client.css;

import com.google.gwt.dom.client.Style;

/**
 * This property specifies the content width of boxes generated by block-level
 * and replaced elements.
 *
 * This property does not apply to non-replaced inline-level elements. The
 * content width of a non-replaced inline element's boxes is that of the
 * rendered content within them (before any relative offset of children). Recall
 * that inline boxes flow into line boxes. The width of line boxes is given by
 * the their containing block, but may be shorted by the presence of floats.
 *
 * The width of a replaced element's box is intrinsic and may be scaled by the
 * user agent if the value of this property is different than 'auto'.
 */
public class Width implements TakesLength, TakesPercentage {

  public static void init() {
    CSS.WIDTH = new Width();
  }

  public void set(Style s, Length value) {
    s.setProperty("width", value.value());
  }

  public String get(Style s) {
    return s.getProperty("width");
  }

  public void setLength(Style s, Length p) {
    s.setProperty("width", p.value());
  }

  public void setPercentage(Style s, Percentage p) {
    s.setProperty("width", p.value());
  }
}
